## What is Numpy?
#### Numpy (Numerical Python) is a core library for scientific and numerical computing in Python.

## Why use Numpy?
- Fast : Works with Large, multi Dimensional Arrays stored in continuguous memory blocks
- Effecient : Operations are optimized via 'C' under the hood.
- Foundational : Powered with many Scientific Libraries (eg. Pandas, Scipy , Tensorflow)

### Numpy Also:
- offers the statistical tools like - mean, median, std, variance , etc.
- Intergrates well with Visualization Libraries Like - Matplotlib.

In [2]:
import numpy as np
dir(np)

['ALLOW_THREADS',
 'BUFSIZE',
 'CLIP',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'WRAP',
 '_CopyMode',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__former_attrs__',
 '__future_scalars__',
 '__getattr__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_add_newdoc_ufunc',
 '_builtins',
 '_distributor_init',
 '_financi

In [3]:
num = np.array([11,22,33,44,55,66,77,88,99])
print(num)

[11 22 33 44 55 66 77 88 99]


In [4]:
# Indexation starts with 0
num[5] # 66

66

In [6]:
num[-1] #99

99

In [8]:
num[-3] # 77

77

In [9]:
arr_from_list = np.array([11,22,33,44,55,66,77,88,99])
arr_from_tuple = np.array((11,22,33,44,55,66,77,88,99))
print(arr_from_list)
print(arr_from_tuple)

[11 22 33 44 55 66 77 88 99]
[11 22 33 44 55 66 77 88 99]


In [15]:
arr_from_tuple = np.array(11)
arr_from_tuple 

array(11)

In [16]:
print(type(arr_from_list))
print(type(arr_from_tuple))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [17]:
arr_from_list.ndim

1

In [18]:
# 1D Array
arr_1d = np.array([11,121.9,True,'k','Coding',11+5j,99]) # mixed dtypes
print(arr_1d)

['11' '121.9' 'True' 'k' 'Coding' '(11+5j)' '99']


In [19]:
type(arr_1d)

numpy.ndarray

In [20]:
print(type(arr_1d))

<class 'numpy.ndarray'>


In [22]:
arr_1d.dtype

dtype('<U64')

In [23]:
arr_1d.ndim

1

In [24]:
# 2D Array [2 Dimensional] [rows, cols] (n*m) (5,3)
arr_2d = np.array([
   [11,22,33] ,
   ['a','b','c'] ,
   [True,False,True] ,
   ['learn','python','programming'] ,
   [9.99,11.11,77.77] 
]) # Mixed dtypes [maintaining 15 elements] [rows * cols] = 5*3 = 15
print(arr_2d)

[['11' '22' '33']
 ['a' 'b' 'c']
 ['True' 'False' 'True']
 ['learn' 'python' 'programming']
 ['9.99' '11.11' '77.77']]


In [25]:
print(type(arr_2d))

<class 'numpy.ndarray'>


In [27]:
arr_2d.dtype

dtype('<U32')

In [28]:
arr_2d.ndim # 2

2

In [41]:
# 1D Array -> U32/U64 -> to the max length of a string
arr_1d = np.array([11,121.9,True,'k','Coding',11+5j,99,
                   'Awek$#@##@lkdsahbk2972ry3oFWuighaslk7238rghjv,cadbvdsck.hvalgbvsablviabha,dsbv12']) # mixed dtypes
print(arr_1d)

['11' '121.9' 'True' 'k' 'Coding' '(11+5j)' '99'
 'Awek$#@##@lkdsahbk2972ry3oFWuighaslk7238rghjv,cadbvdsck.hvalgbvsablviabha,dsbv12']


In [42]:
arr_1d.dtype

dtype('<U80')

In [43]:
arr_1d = np.array(['Python Programming',
                   'Today, We are learning Numpy Array']) # mixed dtypes
print(arr_1d)

['Python Programming' 'Today, We are learning Numpy Array']


In [45]:
arr_1d.dtype

dtype('<U34')

In [46]:
arr_1d = np.array(['Python Programming',99,77]) # mixed dtypes
print(arr_1d)

['Python Programming' '99' '77']


In [47]:
arr_1d.dtype

dtype('<U18')

In [48]:
# 3D Array [3 Dimensional] [depth ,rows, cols] (d*n*m)  = Total Number of Elements
# 3 depth , 3 rows , 3 columns
arr_3d = np.array([
    [[1,2,3],
    [2,4,6],
    [1,3,5]],
    
    [['a','b','c'],
    ['d','e','f'],
    ['g','h','i']],
    
    [[True,True,True],
    [True,False,True],
    [False,False,False]]
])
print(arr_3d)

[[['1' '2' '3']
  ['2' '4' '6']
  ['1' '3' '5']]

 [['a' 'b' 'c']
  ['d' 'e' 'f']
  ['g' 'h' 'i']]

 [['True' 'True' 'True']
  ['True' 'False' 'True']
  ['False' 'False' 'False']]]


In [49]:
type(arr_3d)

numpy.ndarray

In [50]:
arr_3d.dtype

dtype('<U11')

In [51]:
arr_3d.ndim

3

In [52]:
# 27 = 3*3*3
arr_1d = np.array([1,2,3,4,5,6,7,8,9,9,8,7,6,5,4,3,2,1,1,2,3,4,5,6,7,8,9])
print(arr_1d)

[1 2 3 4 5 6 7 8 9 9 8 7 6 5 4 3 2 1 1 2 3 4 5 6 7 8 9]


In [53]:
# 3D reshape (depth,rows,cols) - (3,3,3)
arr_1d.reshape(3,3,3)

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[9, 8, 7],
        [6, 5, 4],
        [3, 2, 1]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [55]:
# Specifying Data Types [Upcasting]
nested_list = np.array([
    [11,22],
    [33,44],
    [55,66],
    [77,88],
    [99,99.99]
])
print(nested_list)

[[11.   22.  ]
 [33.   44.  ]
 [55.   66.  ]
 [77.   88.  ]
 [99.   99.99]]


In [56]:
nested_list = np.array([
    [11,22],
    [33,44],
    [55,66],
    [77,88],
    [99,121]
])
float_arr = np.array(nested_list , dtype = float)
print(float_arr)

[[ 11.  22.]
 [ 33.  44.]
 [ 55.  66.]
 [ 77.  88.]
 [ 99. 121.]]


In [57]:
# upcast ['str'] VS dtype ['float']
nested_list = np.array([
    [11,22],
    [33,44],
    [55,66],
    [77,88],
    ['99.99','121']
])
float_arr = np.array(nested_list , dtype = float)
print(float_arr)

[[ 11.    22.  ]
 [ 33.    44.  ]
 [ 55.    66.  ]
 [ 77.    88.  ]
 [ 99.99 121.  ]]


In [62]:
# upcast ['str'] VS dtype ['float']
nested_list = np.array([
    [11,22],
    [33,44],
    [55,66],
    [77,88],
    [False,True]
])
float_arr = np.array(nested_list , dtype = float)
print(float_arr)

[[11. 22.]
 [33. 44.]
 [55. 66.]
 [77. 88.]
 [ 0.  1.]]


In [63]:
float_arr.dtype

dtype('float64')

In [64]:
# ndarray [N-Dimensional Array] -> [.shape]
arr_1d.shape

(27,)

In [65]:
arr_2d.shape

(5, 3)

In [67]:
arr_3d.shape # 3d [depth,rows,cols]

(3, 3, 3)

In [68]:
# .size Attribute -> Total Numbers of Elements 
arr_1d.size

27

In [69]:
arr_2d.size

15

In [70]:
arr_3d.size

27

In [71]:
# Reshape 1D -> 4D [2,2,2,2] = 2*2*2*2 = 16 elements
arr_1d = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16])
print(arr_1d)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]


In [72]:
arr_1d.reshape(2,4,2) # 3D

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12],
        [13, 14],
        [15, 16]]])

In [73]:
arr_1d.reshape(2,2,4) # 3D

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

In [74]:
arr_1d.reshape(2,2,2,2) # 4D

array([[[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]]],


       [[[ 9, 10],
         [11, 12]],

        [[13, 14],
         [15, 16]]]])