## What is Numpy?
#### Numpy (Numerical Python) is a core library for scientific and numerical computing in Python.

## Why use Numpy?
- Fast : Works with Large, multi Dimensional Arrays stored in continuguous memory blocks
- Effecient : Operations are optimized via 'C' under the hood.
- Foundational : Powered with many Scientific Libraries (eg. Pandas, Scipy , Tensorflow)

### Numpy Also:
- offers the statistical tools like - mean, median, std, variance , etc.
- Intergrates well with Visualization Libraries Like - Matplotlib.

In [2]:
import numpy as np
dir(np)

['ALLOW_THREADS',
 'BUFSIZE',
 'CLIP',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'WRAP',
 '_CopyMode',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__former_attrs__',
 '__future_scalars__',
 '__getattr__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_add_newdoc_ufunc',
 '_builtins',
 '_distributor_init',
 '_financi

In [3]:
num = np.array([11,22,33,44,55,66,77,88,99])
print(num)

[11 22 33 44 55 66 77 88 99]


In [4]:
# Indexation starts with 0
num[5] # 66

66

In [6]:
num[-1] #99

99

In [8]:
num[-3] # 77

77

In [9]:
arr_from_list = np.array([11,22,33,44,55,66,77,88,99])
arr_from_tuple = np.array((11,22,33,44,55,66,77,88,99))
print(arr_from_list)
print(arr_from_tuple)

[11 22 33 44 55 66 77 88 99]
[11 22 33 44 55 66 77 88 99]


In [15]:
arr_from_tuple = np.array(11)
arr_from_tuple 

array(11)

In [16]:
print(type(arr_from_list))
print(type(arr_from_tuple))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [17]:
arr_from_list.ndim

1

In [18]:
# 1D Array
arr_1d = np.array([11,121.9,True,'k','Coding',11+5j,99]) # mixed dtypes
print(arr_1d)

['11' '121.9' 'True' 'k' 'Coding' '(11+5j)' '99']


In [19]:
type(arr_1d)

numpy.ndarray

In [20]:
print(type(arr_1d))

<class 'numpy.ndarray'>


In [22]:
arr_1d.dtype

dtype('<U64')

In [23]:
arr_1d.ndim

1

In [24]:
# 2D Array [2 Dimensional] [rows, cols] (n*m) (5,3)
arr_2d = np.array([
   [11,22,33] ,
   ['a','b','c'] ,
   [True,False,True] ,
   ['learn','python','programming'] ,
   [9.99,11.11,77.77] 
]) # Mixed dtypes [maintaining 15 elements] [rows * cols] = 5*3 = 15
print(arr_2d)

[['11' '22' '33']
 ['a' 'b' 'c']
 ['True' 'False' 'True']
 ['learn' 'python' 'programming']
 ['9.99' '11.11' '77.77']]


In [25]:
print(type(arr_2d))

<class 'numpy.ndarray'>


In [27]:
arr_2d.dtype

dtype('<U32')

In [28]:
arr_2d.ndim # 2

2

In [41]:
# 1D Array -> U32/U64 -> to the max length of a string
arr_1d = np.array([11,121.9,True,'k','Coding',11+5j,99,
                   'Awek$#@##@lkdsahbk2972ry3oFWuighaslk7238rghjv,cadbvdsck.hvalgbvsablviabha,dsbv12']) # mixed dtypes
print(arr_1d)

['11' '121.9' 'True' 'k' 'Coding' '(11+5j)' '99'
 'Awek$#@##@lkdsahbk2972ry3oFWuighaslk7238rghjv,cadbvdsck.hvalgbvsablviabha,dsbv12']


In [42]:
arr_1d.dtype

dtype('<U80')

In [43]:
arr_1d = np.array(['Python Programming',
                   'Today, We are learning Numpy Array']) # mixed dtypes
print(arr_1d)

['Python Programming' 'Today, We are learning Numpy Array']


In [45]:
arr_1d.dtype

dtype('<U34')

In [46]:
arr_1d = np.array(['Python Programming',99,77]) # mixed dtypes
print(arr_1d)

['Python Programming' '99' '77']


In [47]:
arr_1d.dtype

dtype('<U18')

In [48]:
# 3D Array [3 Dimensional] [depth ,rows, cols] (d*n*m)  = Total Number of Elements
# 3 depth , 3 rows , 3 columns
arr_3d = np.array([
    [[1,2,3],
    [2,4,6],
    [1,3,5]],
    
    [['a','b','c'],
    ['d','e','f'],
    ['g','h','i']],
    
    [[True,True,True],
    [True,False,True],
    [False,False,False]]
])
print(arr_3d)

[[['1' '2' '3']
  ['2' '4' '6']
  ['1' '3' '5']]

 [['a' 'b' 'c']
  ['d' 'e' 'f']
  ['g' 'h' 'i']]

 [['True' 'True' 'True']
  ['True' 'False' 'True']
  ['False' 'False' 'False']]]


In [49]:
type(arr_3d)

numpy.ndarray

In [50]:
arr_3d.dtype

dtype('<U11')

In [51]:
arr_3d.ndim

3

In [52]:
# 27 = 3*3*3
arr_1d = np.array([1,2,3,4,5,6,7,8,9,9,8,7,6,5,4,3,2,1,1,2,3,4,5,6,7,8,9])
print(arr_1d)

[1 2 3 4 5 6 7 8 9 9 8 7 6 5 4 3 2 1 1 2 3 4 5 6 7 8 9]


In [53]:
# 3D reshape (depth,rows,cols) - (3,3,3)
arr_1d.reshape(3,3,3)

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[9, 8, 7],
        [6, 5, 4],
        [3, 2, 1]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [55]:
# Specifying Data Types [Upcasting]
nested_list = np.array([
    [11,22],
    [33,44],
    [55,66],
    [77,88],
    [99,99.99]
])
print(nested_list)

[[11.   22.  ]
 [33.   44.  ]
 [55.   66.  ]
 [77.   88.  ]
 [99.   99.99]]


In [56]:
nested_list = np.array([
    [11,22],
    [33,44],
    [55,66],
    [77,88],
    [99,121]
])
float_arr = np.array(nested_list , dtype = float)
print(float_arr)

[[ 11.  22.]
 [ 33.  44.]
 [ 55.  66.]
 [ 77.  88.]
 [ 99. 121.]]


In [57]:
# upcast ['str'] VS dtype ['float']
nested_list = np.array([
    [11,22],
    [33,44],
    [55,66],
    [77,88],
    ['99.99','121']
])
float_arr = np.array(nested_list , dtype = float)
print(float_arr)

[[ 11.    22.  ]
 [ 33.    44.  ]
 [ 55.    66.  ]
 [ 77.    88.  ]
 [ 99.99 121.  ]]


In [62]:
# upcast ['str'] VS dtype ['float']
nested_list = np.array([
    [11,22],
    [33,44],
    [55,66],
    [77,88],
    [False,True]
])
float_arr = np.array(nested_list , dtype = float)
print(float_arr)

[[11. 22.]
 [33. 44.]
 [55. 66.]
 [77. 88.]
 [ 0.  1.]]


In [63]:
float_arr.dtype

dtype('float64')

In [64]:
# ndarray [N-Dimensional Array] -> [.shape]
arr_1d.shape

(27,)

In [65]:
arr_2d.shape

(5, 3)

In [67]:
arr_3d.shape # 3d [depth,rows,cols]

(3, 3, 3)

In [68]:
# .size Attribute -> Total Numbers of Elements 
arr_1d.size

27

In [69]:
arr_2d.size

15

In [70]:
arr_3d.size

27

In [71]:
# Reshape 1D -> 4D [2,2,2,2] = 2*2*2*2 = 16 elements
arr_1d = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16])
print(arr_1d)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]


In [72]:
arr_1d.reshape(2,4,2) # 3D

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12],
        [13, 14],
        [15, 16]]])

In [73]:
arr_1d.reshape(2,2,4) # 3D

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

In [74]:
arr_1d.reshape(2,2,2,2) # 4D

array([[[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]]],


       [[[ 9, 10],
         [11, 12]],

        [[13, 14],
         [15, 16]]]])

In [1]:
# ndarray.itemsize Attribute -> Memory Size of Each Elements (in Bytes)
import numpy as np
arr_int = np.array([1,2,3,5,7,9,11,15,21,29,55,77,99] , dtype = int)
print(arr_int.itemsize, "bytes")

4 bytes


In [2]:
arr_float = np.array([1.9999,2.1111,3,5,7,9,11,15,21,29,55,77.777,99.9999] , dtype = float)
print(arr_float.itemsize, "bytes")

8 bytes


In [3]:
arr_str = np.array(['Coding','Python','Java','Programming','Numpy','Array'], dtype = str)
print(arr_str.itemsize , "bytes")

44 bytes


In [4]:
arr_str = np.array(['Coding','Python','Java','hello'], dtype = str)
print(arr_str.itemsize , "bytes")

24 bytes


In [7]:
# ndarray.data -> Memory Location [Buffer]
arr = np.array([11,22,33,44,55,66,77])
print("Data Buffer:" , arr.data) # Memory Location
print("Type of Buffer:" , type(arr.data)) # Memory View

Data Buffer: <memory at 0x000001C2F3F6AB00>
Type of Buffer: <class 'memoryview'>


In [9]:
# Indexing, Slicing, Operations on Numpy Array
arr_1d = np.array([11,22,33,44,55])
print(arr_1d[2]) # 33
print(arr_1d[-2]) # 44
print(arr_1d[-5]) # 11
# print(arr_1d[5]) # IndexError: index 5 is out of bounds for axis 0 with size 5
print(arr_1d[0]) # 11

33
44
11
11


In [12]:
# reshape [4,5] 4 rows and 5 columns = [item size = row * col] = 4*5 = 20
arr_2d = np.array([
    [1,2,3,4,5],
    [1,3,5,7,9],
    [2,4,6,8,0],
    [5,4,3,2,1]
])
# indexing[row,col]
# print(arr_2d[5,0]) # IndexError: index 5 is out of bounds for axis 0 ['row'] with size 4
print(arr_2d[-1,-1]) # 1
# print(arr_2d[1,5]) # IndexError Col Index out of bounds for axis 1 ['col']
print(arr_2d[-3,-2]) # 7 'Thala for a reason'
print(arr_2d[2,4]) # 0 
print(arr_2d[3,-5]) # 5
# print(arr_2d[4,4]) # IndexError: index 4 is out of bounds for axis 0 with size 4
print(arr_2d[-3,-3]) # 5
print(arr_2d[-2,1]) # 4

1
7
0
5
5
4


In [14]:
# Shape of a 3D Array[2,3,4] => 2(depth), 3(rows), 4(columns)
arr_3d = np.array([
    [[11,22,33,44],
     [22,44,66,88],
     [11,33,55,77],
    ],
    [[66,77,88,99],
     [11,55,77,99],
     [22,44,66,88],
    ]
])
# Indexing[depth,rows,cols]
print(arr_3d[-1,2,3]) # 88
print(arr_3d[-2,-3,-4]) # 11
# print(arr_3d[0,3,2]) # IndexError: index 3 is out of bounds for axis 0 with size 3
# print(arr_3d[-2,0,4]) # IndexError: index 4 is out of bounds for axis 1 with size 4
print(arr_3d[1,2,-3]) # 44
print(arr_3d[0,-1,-1]) # 77
print(arr_3d[-2,1,-4]) # 22
print(arr_3d[0,-3,3]) # 44

88
11
44
77
22
44


In [20]:
# Slicing [start = 0 , stop : till the length [Exclusive] , step = 1]
arr_1d = np.array([11,22,33,44,55,66,77,88,99])
print(arr_1d[-3:]) # [77,88,99]
print(arr_1d[-3::-1]) # [77,.....11]
print(arr_1d[-3:9:-1]) # []
print(arr_1d[-3:-6:-1]) # [77,66,55]
print(arr_1d[-3:0:-1]) # [77,66,55,44,33,22]
print(arr_1d[5:4:2]) # []
print(arr_1d[5:9:2]) # [66,88]
print(arr_1d[8:0:-2]) # [99,77,55,33]
print(arr_1d[-4::-2]) # [66,44,22]
print(arr_1d[3:8:-3]) # []
print(arr_1d[5:11:2]) # [66,88]

[77 88 99]
[77 66 55 44 33 22 11]
[]
[77 66 55]
[77 66 55 44 33 22]
[]
[66 88]
[99 77 55 33]
[66 44 22]
[]
[66 88]


In [21]:
# slicing[start,stop,step] -> arr_2d[rows_slicing , columns_slicing ]
arr_2d = np.array([
    [1,2,3,4,5],
    [1,3,5,7,9],
    [2,4,6,8,0],
    [5,4,3,2,1]
])

print(arr_2d[1:3 , 2:4]) # [[5,7][6,8]]

[[5 7]
 [6 8]]


In [22]:
print(arr_2d[-3::1 , 3::-1]) # [[7,5,3,1][8,6,4,2][2,3,4,5]]

[[7 5 3 1]
 [8 6 4 2]
 [2 3 4 5]]


In [23]:
arr_2d = np.array([
    [1,2,3,4,5],
    [1,3,5,7,9],
    [2,4,6,8,0],
    [5,4,3,2,1]
])

print(arr_2d[3::-2 , 1:4:3]) # [[4][3]]
# [5,4,3,2,1]
# [1,3,5,7,9]

[[4]
 [3]]


In [24]:
arr_2d = np.array([
    [1,2,3,4,5],
    [1,3,5,7,9],
    [2,4,6,8,0],
    [5,4,3,2,1]
])

print(arr_2d[2:5 , 2:5:-2]) # []
#  [2,4,6,8,0]
#  [5,4,3,2,1]

[]


In [25]:
arr_2d = np.array([
    [1,2,3,4,5],
    [1,3,5,7,9],
    [2,4,6,8,0],
    [5,4,3,2,1]
])

print(arr_2d[2:5 , 2:5:2]) # [[6,0][3,1]]
#  [2,4,6,8,0]
#  [5,4,3,2,1]

[[6 0]
 [3 1]]


In [26]:
arr_2d = np.array([
    [1,2,3,4,5],
    [1,3,5,7,9],
    [2,4,6,8,0],
    [5,4,3,2,1]
])

print(arr_2d[:, ::-2])

[[5 3 1]
 [9 5 1]
 [0 6 2]
 [1 3 5]]


In [27]:
arr_2d = np.array([
    [1,2,3,4,5],
    [1,3,5,7,9],
    [2,4,6,8,0],
    [5,4,3,2,1]
])

print(arr_2d[::-1, ::-1])
# First Row Reverse
# [5,4,3,2,1]
# [2,4,6,8,0]
# [1,3,5,7,9]
# [1,2,3,4,5]

# Then Column Reverse
# [1,2,3,4,5]
# [0,8,6,4,2]
# [9,7,5,3,1]
# [5,4,3,2,1]

[[1 2 3 4 5]
 [0 8 6 4 2]
 [9 7 5 3 1]
 [5 4 3 2 1]]


In [28]:
# Slicing in 3D Array [depth,row,col] -> [depth_slicing , row_slicing , col_slicing]
arr_3d = np.array([
    [[11,22,33,44],
     [22,44,66,88],
     [11,33,55,77],
    ],
    [[66,77,88,99],
     [11,55,77,99],
     [22,44,66,88],
    ]
])
arr_3d[:,:,::-1] # Complete 3D Array with reversed Columns

array([[[44, 33, 22, 11],
        [88, 66, 44, 22],
        [77, 55, 33, 11]],

       [[99, 88, 77, 66],
        [99, 77, 55, 11],
        [88, 66, 44, 22]]])

In [29]:
arr_3d = np.array([
    [[11,22,33,44],
     [22,44,66,88],
     [11,33,55,77],
    ],
    [[66,77,88,99],
     [11,55,77,99],
     [22,44,66,88],
    ]
])
arr_3d[1::2 , 0:3:2, ::-3] 
# Depth
#      [66,77,88,99],
#      [11,55,77,99],
#      [22,44,66,88]

# rows 
# [66,77,88,99]
# [22,44,66,88]

# Cols
# [99,66]
# [88,22]

array([[[99, 66],
        [88, 22]]])

In [31]:
arr_3d = np.array([
    [[11,22,33,44],
     [22,44,66,88],
     [11,33,55,77],
    ],
    [[66,77,88,99],
     [11,55,77,99],
     [22,44,66,88],
    ]
])
print(arr_3d[-2,2,0]) #  11
arr_3d[-2: , -1: , 0:3:2]

# [11,33,55,77] # [11,55]
# [22,44,66,88] # [22,66]

11


array([[[11, 55]],

       [[22, 66]]])

In [32]:
arr_3d = np.array([
    [[11,22,33,44],
     [22,44,66,88],
     [11,33,55,77],
    ],
    [[66,77,88,99],
     [11,55,77,99],
     [22,44,66,88],
    ]
])
arr_3d[0, -2::2, -3::-2] # 44

array([[44]])

In [33]:
arr_3d = np.array([
    [[11,22,33,44],
     [22,44,66,88],
     [11,33,55,77],
    ],
    [[66,77,88,99],
     [11,55,77,99],
     [22,44,66,88],
    ]
])
arr_3d[-2::2, ::-2 ,2:4:-1] # []

array([], shape=(1, 2, 0), dtype=int32)

In [34]:
arr_3d = np.array([
    [[11,22,33,44],
     [22,44,66,88],
     [11,33,55,77],
    ],
    [[66,77,88,99],
     [11,55,77,99],
     [22,44,66,88],
    ]
])
arr_3d[-2::2, ::-2 ,2:4:]

array([[[55, 77],
        [33, 44]]])

In [35]:
# Masking -> Uses a boolean array of the same shape to filter the values. 
arr_1d = np.array([11,22,33,44,55,66,77,88,99])
mask_arr = np.array([True,False,False,False,True,False,True,False,True])
print(arr_1d[mask_arr]) # [11,55,77,99]

[11 55 77 99]


In [36]:
# arr_2d [Masking]
arr_2d = np.array([
    [1,2,3,4,5],
    [1,3,5,7,9],
    [2,4,6,8,0],
    [5,4,3,2,1]
])

mask_2d = np.array([
    [True,False,True,True,True],
    [False,True,True,False,True],
    [True,False,True,True,False],
    [True,False,False,True,False]
])
print(arr_2d[mask_2d]) # Flatten up

[1 3 4 5 3 5 9 2 6 8 5 2]


In [37]:
arr_3d = np.array([
    [[11,22,33,44],
     [22,44,66,88],
     [11,33,55,77],
    ],
    [[66,77,88,99],
     [11,55,77,99],
     [22,44,66,88],
    ]
])

mask_3d = np.array([
    [[True,False,False,True],
     [False,True,True,False],
     [True,False,True,False],
    ],
    [[False,False,True,True],
     [True,True,False,False],
     [False,True,False,True],
    ]
])

print(arr_3d[mask_3d])

[11 44 44 66 11 55 88 99 11 55 44 88]


In [2]:
import numpy as np
# Ellipsis [...] # can be called only one time -> 3D (depth , rows ,cols)
# 3D [2,5,2]
arr_3d = np.array([
    [[11,22],
    [33,44],
    [55,66],
    [77,88],
    [99,110]],
    
    [[1,2],
    [3,4],
    [5,6],
    [7,8],
    [9,10]],
])
print(arr_3d[...]) # arr_3d[:,:,:]

[[[ 11  22]
  [ 33  44]
  [ 55  66]
  [ 77  88]
  [ 99 110]]

 [[  1   2]
  [  3   4]
  [  5   6]
  [  7   8]
  [  9  10]]]


In [3]:
arr_3d = np.array([
    [[11,22],
    [33,44],
    [55,66],
    [77,88],
    [99,110]],
    
    [[1,2],
    [3,4],
    [5,6],
    [7,8],
    [9,10]],
])
print(arr_3d[... , 1]) # ellipsis -> we are expanding the depth with 1st column

[[ 22  44  66  88 110]
 [  2   4   6   8  10]]


In [4]:
print(arr_3d[: , : , 1])

[[ 22  44  66  88 110]
 [  2   4   6   8  10]]


In [5]:
arr_3d.shape

(2, 5, 2)

In [6]:
arr_3d = np.array([
    [[11,22],
    [33,44],
    [55,66],
    [77,88],
    [99,110]],
    
    [[1,2],
    [3,4],
    [5,6],
    [7,8],
    [9,10]],
])
print(arr_3d[: , 0 , ...])

[[11 22]
 [ 1  2]]


In [7]:
print(arr_3d[: , 0 , :])

[[11 22]
 [ 1  2]]


In [8]:
arr_3d = np.array([
    [[11,22],
    [33,44],
    [55,66],
    [77,88],
    [99,110]],
    
    [[1,2],
    [3,4],
    [5,6],
    [7,8],
    [9,10]],
])
print(arr_3d[..., -1])

[[ 22  44  66  88 110]
 [  2   4   6   8  10]]


In [9]:
print(arr_3d[:, :, -1])

[[ 22  44  66  88 110]
 [  2   4   6   8  10]]


In [10]:
arr_3d = np.array([
    [[11,22],
    [33,44],
    [55,66],
    [77,88],
    [99,110]],
    
    [[1,2],
    [3,4],
    [5,6],
    [7,8],
    [9,10]],
])
print(arr_3d[0, ...]) # 0th depth with all rows and cols

[[ 11  22]
 [ 33  44]
 [ 55  66]
 [ 77  88]
 [ 99 110]]


In [11]:
print(arr_3d[0, : , :])

[[ 11  22]
 [ 33  44]
 [ 55  66]
 [ 77  88]
 [ 99 110]]


In [12]:
# Operation on Arrays 
a = np.array([11,22,33,44,55,66,77,88,99])
b = np.array([7,9,11,17,21,29,41,77,91])

print(a.shape)
print(b.shape)

(9,)
(9,)


In [13]:
# Addition 
print("Numpy Array Addition : ")
a+b

Numpy Array Addition : 


array([ 18,  31,  44,  61,  76,  95, 118, 165, 190])

In [14]:
# Subtraction 
print("Numpy Array Subtraction : ")
a-b

Numpy Array Subtraction : 


array([ 4, 13, 22, 27, 34, 37, 36, 11,  8])

In [15]:
# Multiplication 
print("Numpy Array Multiplication : ")
a*b

Numpy Array Multiplication : 


array([  77,  198,  363,  748, 1155, 1914, 3157, 6776, 9009])

In [16]:
# Division 
print("Numpy Array Divison : ")
a/b

Numpy Array Divison : 


array([1.57142857, 2.44444444, 3.        , 2.58823529, 2.61904762,
       2.27586207, 1.87804878, 1.14285714, 1.08791209])

In [17]:
# Floor Division 
print("Numpy Array Floor Divison : ")
a//b

Numpy Array Floor Divison : 


array([1, 2, 3, 2, 2, 2, 1, 1, 1])

In [18]:
# Modulus: 
print("Numpy Array Modulus : ")
a%b

Numpy Array Modulus : 


array([ 4,  4,  0, 10, 13,  8, 36, 11,  8])

In [21]:
# Exponentiation: 
print("Numpy Array Exponent : ")
a ** 2

Numpy Array Exponent : 


array([ 121,  484, 1089, 1936, 3025, 4356, 5929, 7744, 9801])

In [22]:
print("Numpy Array Exponent : ")
b ** 2

Numpy Array Exponent : 


array([  49,   81,  121,  289,  441,  841, 1681, 5929, 8281])

In [23]:
# Operation on Arrays 
a = np.array([11,22,33,44,55,66,77,88,99])
b = np.array([1,2,3,4,5,6,7])

print(a.shape)
print(b.shape)

(9,)
(7,)


# Transposing Array:
#### Transposing an array swaps its rows and columns, like flipping a matrix along its diagonal

In [27]:
arr_2d = np.array([
    [11,22,33,44,55],
    [99,88,77,66,55],
    [11,33,55,77,99],
    [22,44,66,88,10],
    [10,33,66,77,99]
])
print("Original Array: \n" , arr_2d)

Original Array: 
 [[11 22 33 44 55]
 [99 88 77 66 55]
 [11 33 55 77 99]
 [22 44 66 88 10]
 [10 33 66 77 99]]


In [28]:
print("Transposed Array: \n" , arr_2d.transpose())

Transposed Array: 
 [[11 99 11 22 10]
 [22 88 33 44 33]
 [33 77 55 66 66]
 [44 66 77 88 77]
 [55 55 99 10 99]]


In [29]:
print("Transposed Array: \n" , arr_2d.T)

Transposed Array: 
 [[11 99 11 22 10]
 [22 88 33 44 33]
 [33 77 55 66 66]
 [44 66 77 88 77]
 [55 55 99 10 99]]


# Sorting Arrays:
#### Sorting means arranging elements in ascending (default) or descending order

In [30]:
arr_1d = np.array([22,77,55,11,33,99,44,66,88])
print(arr_1d)
print(np.sort(arr_1d))

[22 77 55 11 33 99 44 66 88]
[11 22 33 44 55 66 77 88 99]


In [33]:
print(np.sort(arr_1d)[::-1]) # Descending Order

[99 88 77 66 55 44 33 22 11]


In [35]:
# Axis = 0 [Horizontal] or axis = 1[Vertical]
arr_2d = np.array([
    [11,22,33,44,55],
    [99,88,77,66,55],
    [11,33,55,77,99],
    [22,44,66,88,10],
    [10,33,66,77,99]
])
np.sort(arr_2d , axis = 0)

array([[10, 22, 33, 44, 10],
       [11, 33, 55, 66, 55],
       [11, 33, 66, 77, 55],
       [22, 44, 66, 77, 99],
       [99, 88, 77, 88, 99]])

In [36]:
# axis = 1[Vertical]
arr_2d = np.array([
    [11,22,33,44,55],
    [99,88,77,66,55],
    [11,33,55,77,99],
    [22,44,66,88,10],
    [10,33,66,77,99]
])
np.sort(arr_2d , axis = 1)

array([[11, 22, 33, 44, 55],
       [55, 66, 77, 88, 99],
       [11, 33, 55, 77, 99],
       [10, 22, 44, 66, 88],
       [10, 33, 66, 77, 99]])

In [37]:
# argsort [indexing Sort]
arr_1d = np.array([55,11,44,33,22])
pos_arr = np.argsort(arr_1d)
print(arr_1d)
print(pos_arr)

[55 11 44 33 22]
[1 4 3 2 0]


In [38]:
print(arr_1d[pos_arr])

[11 22 33 44 55]


In [39]:
arr_1d[1]

11

In [40]:
arr_1d[4]

22

In [41]:
arr_1d[3]

33

In [43]:
# axis = 1[Vertical]
arr_2d = np.array([
    [11,22,33,44,55],
    [99,88,77,66,55],
    [11,33,55,77,99],
    [22,44,66,88,10],
    [10,33,66,77,99]
])
print(arr_2d)
print(np.argsort(arr_2d , axis = 1))

[[11 22 33 44 55]
 [99 88 77 66 55]
 [11 33 55 77 99]
 [22 44 66 88 10]
 [10 33 66 77 99]]
[[0 1 2 3 4]
 [4 3 2 1 0]
 [0 1 2 3 4]
 [4 0 1 2 3]
 [0 1 2 3 4]]


In [44]:
# axis = 0[Horizontal] [rows]
arr_2d = np.array([
    [11,22,33,44,55],
    [99,88,77,66,55],
    [11,33,55,77,99],
    [22,44,66,88,10],
    [10,33,66,77,99]
])
print(arr_2d)
print(np.argsort(arr_2d , axis = 0))

[[11 22 33 44 55]
 [99 88 77 66 55]
 [11 33 55 77 99]
 [22 44 66 88 10]
 [10 33 66 77 99]]
[[4 0 0 0 3]
 [0 2 2 1 0]
 [2 4 3 2 1]
 [3 3 4 4 2]
 [1 1 1 3 4]]


In [47]:
# Concatenating an array -> It means Joining the array - either row wise or column wise
X = np.array([11,22,33,44,55])
Y = np.array([66,77,88,99])
Z = np.array([1,2,3,4,5,6,7,8,9])
print(np.concatenate((X,Y,Z)))

[11 22 33 44 55 66 77 88 99  1  2  3  4  5  6  7  8  9]


In [49]:
# Concatenating an 2D array
arr_2dA = np.array([
    [11,22,33],
    [44,55,66],
    [77,88,99]
]) # shape(3,3)

arr_2dB = np.array([
    [11,22],
    [44,55],
    [77,88]
]) # shape(3,2)

arr_2dC = np.array([
    [11,22,33],
    [44,55,66]
]) # shape(2,3)

In [50]:
print(np.concatenate((arr_2dA , arr_2dC) , axis=0)) # row wise

[[11 22 33]
 [44 55 66]
 [77 88 99]
 [11 22 33]
 [44 55 66]]


In [52]:
print(np.concatenate((arr_2dA , arr_2dB) , axis=1)) # Col wise Concatenation

[[11 22 33 11 22]
 [44 55 66 44 55]
 [77 88 99 77 88]]


In [55]:
for i in range(1,11):
    print(i , end = " ")

1 2 3 4 5 6 7 8 9 10 

In [57]:
# What is Reshaping?
# arange(start = 0 , stop : length[Non-Inclusive] , step = 1)
arr = np.arange(2,21,2) # [2,4,6,8.....20]
arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [58]:
# 10 elements -> reshape
arr_2d = arr.reshape(2,5)
arr_2d

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20]])

In [59]:
# 10 elements -> reshape
arr_2d = arr.reshape(5,2)
arr_2d

array([[ 2,  4],
       [ 6,  8],
       [10, 12],
       [14, 16],
       [18, 20]])

In [62]:
arr = np.arange(1,17,1) # [1,2,3....16]
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [63]:
# 16 elements
arr_2d = arr.reshape(4,4)
arr_2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [65]:
# arr_2d -> arr_3d
arr_3d = arr_2d.reshape(2,4,2)
arr_3d

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12],
        [13, 14],
        [15, 16]]])

In [66]:
# 3D -> 4D Matrix
arr_4d = arr_3d.reshape(2,2,2,2)
arr_4d

array([[[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]]],


       [[[ 9, 10],
         [11, 12]],

        [[13, 14],
         [15, 16]]]])

In [67]:
# 4D -> 2D Matrix
arr_2d = arr_4d.reshape(8,2)
arr_2d

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16]])

In [68]:
# 4D -> 2D Matrix
arr_2d = arr_4d.reshape(2,8)
arr_2d

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16]])

In [69]:
arr_4d

array([[[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]]],


       [[[ 9, 10],
         [11, 12]],

        [[13, 14],
         [15, 16]]]])

In [72]:
# Flattening n-dimensional_array into 1D array
flattened_arr = arr_4d.reshape(-1)
flattened_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [73]:
flattened_arr = arr_2d.reshape(-1)
flattened_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [74]:
flattened_arr = arr_3d.reshape(-1)
flattened_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [75]:
flattened_arr = arr_3d.reshape(-1,1)
flattened_arr

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16]])

In [76]:
# Splitting an Array 
arr = np.arange(2,21,2) # 10 elements [2,4...20]
print(arr)

[ 2  4  6  8 10 12 14 16 18 20]


In [77]:
split_arr = np.split(arr , 5)
print(split_arr)

[array([2, 4]), array([6, 8]), array([10, 12]), array([14, 16]), array([18, 20])]


In [78]:
for data in split_arr:
    print(data)

[2 4]
[6 8]
[10 12]
[14 16]
[18 20]


In [80]:
# Splitting an Array 
arr = np.arange(1,16,1) # 15 elements [1,2,3....15]
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [81]:
split_arr = np.split(arr, 3)
print(split_arr)

[array([1, 2, 3, 4, 5]), array([ 6,  7,  8,  9, 10]), array([11, 12, 13, 14, 15])]


In [82]:
for data in split_arr:
    print(data)

[1 2 3 4 5]
[ 6  7  8  9 10]
[11 12 13 14 15]


In [83]:
# axis = 0[Horizontal] [rows]
arr_2d = np.array([
    [11,22,33,44,55],
    [99,88,77,66,55],
    [11,33,55,77,99],
    [22,44,66,88,10],
    [10,33,66,77,99]
])

split_arr = np.split(arr_2d , 5 , axis = 0) # row-wise split
split_arr

[array([[11, 22, 33, 44, 55]]),
 array([[99, 88, 77, 66, 55]]),
 array([[11, 33, 55, 77, 99]]),
 array([[22, 44, 66, 88, 10]]),
 array([[10, 33, 66, 77, 99]])]

In [84]:
for data in split_arr:
    print(data)

[[11 22 33 44 55]]
[[99 88 77 66 55]]
[[11 33 55 77 99]]
[[22 44 66 88 10]]
[[10 33 66 77 99]]


In [88]:
# axis = 1 [Vertical] [columns]
arr_2d = np.array([
    [11,22,33,44,55],
    [99,88,77,66,55],
    [11,33,55,77,99],
    [22,44,66,88,10],
    [10,33,66,77,99]
])

split_arr = np.split(arr_2d , 5 , axis = 1) # col-wise split
split_arr

[array([[11],
        [99],
        [11],
        [22],
        [10]]),
 array([[22],
        [88],
        [33],
        [44],
        [33]]),
 array([[33],
        [77],
        [55],
        [66],
        [66]]),
 array([[44],
        [66],
        [77],
        [88],
        [77]]),
 array([[55],
        [55],
        [99],
        [10],
        [99]])]

In [89]:
for data in split_arr:
    print(data)

[[11]
 [99]
 [11]
 [22]
 [10]]
[[22]
 [88]
 [33]
 [44]
 [33]]
[[33]
 [77]
 [55]
 [66]
 [66]]
[[44]
 [66]
 [77]
 [88]
 [77]]
[[55]
 [55]
 [99]
 [10]
 [99]]
