## What is Numpy?
#### Numpy (Numerical Python) is a core library for scientific and numerical computing in Python.

## Why use Numpy?
- Fast : Works with Large, multi Dimensional Arrays stored in continuguous memory blocks
- Effecient : Operations are optimized via 'C' under the hood.
- Foundational : Powered with many Scientific Libraries (eg. Pandas, Scipy , Tensorflow)

### Numpy Also:
- offers the statistical tools like - mean, median, std, variance , etc.
- Intergrates well with Visualization Libraries Like - Matplotlib.

In [2]:
import numpy as np
dir(np)

['ALLOW_THREADS',
 'BUFSIZE',
 'CLIP',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'WRAP',
 '_CopyMode',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__former_attrs__',
 '__future_scalars__',
 '__getattr__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_add_newdoc_ufunc',
 '_builtins',
 '_distributor_init',
 '_financi

In [3]:
num = np.array([11,22,33,44,55,66,77,88,99])
print(num)

[11 22 33 44 55 66 77 88 99]


In [4]:
# Indexation starts with 0
num[5] # 66

66

In [6]:
num[-1] #99

99

In [8]:
num[-3] # 77

77

In [9]:
arr_from_list = np.array([11,22,33,44,55,66,77,88,99])
arr_from_tuple = np.array((11,22,33,44,55,66,77,88,99))
print(arr_from_list)
print(arr_from_tuple)

[11 22 33 44 55 66 77 88 99]
[11 22 33 44 55 66 77 88 99]


In [15]:
arr_from_tuple = np.array(11)
arr_from_tuple 

array(11)

In [16]:
print(type(arr_from_list))
print(type(arr_from_tuple))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [17]:
arr_from_list.ndim

1

In [18]:
# 1D Array
arr_1d = np.array([11,121.9,True,'k','Coding',11+5j,99]) # mixed dtypes
print(arr_1d)

['11' '121.9' 'True' 'k' 'Coding' '(11+5j)' '99']


In [19]:
type(arr_1d)

numpy.ndarray

In [20]:
print(type(arr_1d))

<class 'numpy.ndarray'>


In [22]:
arr_1d.dtype

dtype('<U64')

In [23]:
arr_1d.ndim

1

In [24]:
# 2D Array [2 Dimensional] [rows, cols] (n*m) (5,3)
arr_2d = np.array([
   [11,22,33] ,
   ['a','b','c'] ,
   [True,False,True] ,
   ['learn','python','programming'] ,
   [9.99,11.11,77.77] 
]) # Mixed dtypes [maintaining 15 elements] [rows * cols] = 5*3 = 15
print(arr_2d)

[['11' '22' '33']
 ['a' 'b' 'c']
 ['True' 'False' 'True']
 ['learn' 'python' 'programming']
 ['9.99' '11.11' '77.77']]


In [25]:
print(type(arr_2d))

<class 'numpy.ndarray'>


In [27]:
arr_2d.dtype

dtype('<U32')

In [28]:
arr_2d.ndim # 2

2

In [41]:
# 1D Array -> U32/U64 -> to the max length of a string
arr_1d = np.array([11,121.9,True,'k','Coding',11+5j,99,
                   'Awek$#@##@lkdsahbk2972ry3oFWuighaslk7238rghjv,cadbvdsck.hvalgbvsablviabha,dsbv12']) # mixed dtypes
print(arr_1d)

['11' '121.9' 'True' 'k' 'Coding' '(11+5j)' '99'
 'Awek$#@##@lkdsahbk2972ry3oFWuighaslk7238rghjv,cadbvdsck.hvalgbvsablviabha,dsbv12']


In [42]:
arr_1d.dtype

dtype('<U80')

In [43]:
arr_1d = np.array(['Python Programming',
                   'Today, We are learning Numpy Array']) # mixed dtypes
print(arr_1d)

['Python Programming' 'Today, We are learning Numpy Array']


In [45]:
arr_1d.dtype

dtype('<U34')

In [46]:
arr_1d = np.array(['Python Programming',99,77]) # mixed dtypes
print(arr_1d)

['Python Programming' '99' '77']


In [47]:
arr_1d.dtype

dtype('<U18')

In [48]:
# 3D Array [3 Dimensional] [depth ,rows, cols] (d*n*m)  = Total Number of Elements
# 3 depth , 3 rows , 3 columns
arr_3d = np.array([
    [[1,2,3],
    [2,4,6],
    [1,3,5]],
    
    [['a','b','c'],
    ['d','e','f'],
    ['g','h','i']],
    
    [[True,True,True],
    [True,False,True],
    [False,False,False]]
])
print(arr_3d)

[[['1' '2' '3']
  ['2' '4' '6']
  ['1' '3' '5']]

 [['a' 'b' 'c']
  ['d' 'e' 'f']
  ['g' 'h' 'i']]

 [['True' 'True' 'True']
  ['True' 'False' 'True']
  ['False' 'False' 'False']]]


In [49]:
type(arr_3d)

numpy.ndarray

In [50]:
arr_3d.dtype

dtype('<U11')

In [51]:
arr_3d.ndim

3

In [52]:
# 27 = 3*3*3
arr_1d = np.array([1,2,3,4,5,6,7,8,9,9,8,7,6,5,4,3,2,1,1,2,3,4,5,6,7,8,9])
print(arr_1d)

[1 2 3 4 5 6 7 8 9 9 8 7 6 5 4 3 2 1 1 2 3 4 5 6 7 8 9]


In [53]:
# 3D reshape (depth,rows,cols) - (3,3,3)
arr_1d.reshape(3,3,3)

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[9, 8, 7],
        [6, 5, 4],
        [3, 2, 1]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [55]:
# Specifying Data Types [Upcasting]
nested_list = np.array([
    [11,22],
    [33,44],
    [55,66],
    [77,88],
    [99,99.99]
])
print(nested_list)

[[11.   22.  ]
 [33.   44.  ]
 [55.   66.  ]
 [77.   88.  ]
 [99.   99.99]]


In [56]:
nested_list = np.array([
    [11,22],
    [33,44],
    [55,66],
    [77,88],
    [99,121]
])
float_arr = np.array(nested_list , dtype = float)
print(float_arr)

[[ 11.  22.]
 [ 33.  44.]
 [ 55.  66.]
 [ 77.  88.]
 [ 99. 121.]]


In [57]:
# upcast ['str'] VS dtype ['float']
nested_list = np.array([
    [11,22],
    [33,44],
    [55,66],
    [77,88],
    ['99.99','121']
])
float_arr = np.array(nested_list , dtype = float)
print(float_arr)

[[ 11.    22.  ]
 [ 33.    44.  ]
 [ 55.    66.  ]
 [ 77.    88.  ]
 [ 99.99 121.  ]]


In [62]:
# upcast ['str'] VS dtype ['float']
nested_list = np.array([
    [11,22],
    [33,44],
    [55,66],
    [77,88],
    [False,True]
])
float_arr = np.array(nested_list , dtype = float)
print(float_arr)

[[11. 22.]
 [33. 44.]
 [55. 66.]
 [77. 88.]
 [ 0.  1.]]


In [63]:
float_arr.dtype

dtype('float64')

In [64]:
# ndarray [N-Dimensional Array] -> [.shape]
arr_1d.shape

(27,)

In [65]:
arr_2d.shape

(5, 3)

In [67]:
arr_3d.shape # 3d [depth,rows,cols]

(3, 3, 3)

In [68]:
# .size Attribute -> Total Numbers of Elements 
arr_1d.size

27

In [69]:
arr_2d.size

15

In [70]:
arr_3d.size

27

In [71]:
# Reshape 1D -> 4D [2,2,2,2] = 2*2*2*2 = 16 elements
arr_1d = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16])
print(arr_1d)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]


In [72]:
arr_1d.reshape(2,4,2) # 3D

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12],
        [13, 14],
        [15, 16]]])

In [73]:
arr_1d.reshape(2,2,4) # 3D

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

In [74]:
arr_1d.reshape(2,2,2,2) # 4D

array([[[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]]],


       [[[ 9, 10],
         [11, 12]],

        [[13, 14],
         [15, 16]]]])

In [1]:
# ndarray.itemsize Attribute -> Memory Size of Each Elements (in Bytes)
import numpy as np
arr_int = np.array([1,2,3,5,7,9,11,15,21,29,55,77,99] , dtype = int)
print(arr_int.itemsize, "bytes")

4 bytes


In [2]:
arr_float = np.array([1.9999,2.1111,3,5,7,9,11,15,21,29,55,77.777,99.9999] , dtype = float)
print(arr_float.itemsize, "bytes")

8 bytes


In [3]:
arr_str = np.array(['Coding','Python','Java','Programming','Numpy','Array'], dtype = str)
print(arr_str.itemsize , "bytes")

44 bytes


In [4]:
arr_str = np.array(['Coding','Python','Java','hello'], dtype = str)
print(arr_str.itemsize , "bytes")

24 bytes


In [7]:
# ndarray.data -> Memory Location [Buffer]
arr = np.array([11,22,33,44,55,66,77])
print("Data Buffer:" , arr.data) # Memory Location
print("Type of Buffer:" , type(arr.data)) # Memory View

Data Buffer: <memory at 0x000001C2F3F6AB00>
Type of Buffer: <class 'memoryview'>


In [9]:
# Indexing, Slicing, Operations on Numpy Array
arr_1d = np.array([11,22,33,44,55])
print(arr_1d[2]) # 33
print(arr_1d[-2]) # 44
print(arr_1d[-5]) # 11
# print(arr_1d[5]) # IndexError: index 5 is out of bounds for axis 0 with size 5
print(arr_1d[0]) # 11

33
44
11
11


In [12]:
# reshape [4,5] 4 rows and 5 columns = [item size = row * col] = 4*5 = 20
arr_2d = np.array([
    [1,2,3,4,5],
    [1,3,5,7,9],
    [2,4,6,8,0],
    [5,4,3,2,1]
])
# indexing[row,col]
# print(arr_2d[5,0]) # IndexError: index 5 is out of bounds for axis 0 ['row'] with size 4
print(arr_2d[-1,-1]) # 1
# print(arr_2d[1,5]) # IndexError Col Index out of bounds for axis 1 ['col']
print(arr_2d[-3,-2]) # 7 'Thala for a reason'
print(arr_2d[2,4]) # 0 
print(arr_2d[3,-5]) # 5
# print(arr_2d[4,4]) # IndexError: index 4 is out of bounds for axis 0 with size 4
print(arr_2d[-3,-3]) # 5
print(arr_2d[-2,1]) # 4

1
7
0
5
5
4


In [14]:
# Shape of a 3D Array[2,3,4] => 2(depth), 3(rows), 4(columns)
arr_3d = np.array([
    [[11,22,33,44],
     [22,44,66,88],
     [11,33,55,77],
    ],
    [[66,77,88,99],
     [11,55,77,99],
     [22,44,66,88],
    ]
])
# Indexing[depth,rows,cols]
print(arr_3d[-1,2,3]) # 88
print(arr_3d[-2,-3,-4]) # 11
# print(arr_3d[0,3,2]) # IndexError: index 3 is out of bounds for axis 0 with size 3
# print(arr_3d[-2,0,4]) # IndexError: index 4 is out of bounds for axis 1 with size 4
print(arr_3d[1,2,-3]) # 44
print(arr_3d[0,-1,-1]) # 77
print(arr_3d[-2,1,-4]) # 22
print(arr_3d[0,-3,3]) # 44

88
11
44
77
22
44


In [20]:
# Slicing [start = 0 , stop : till the length [Exclusive] , step = 1]
arr_1d = np.array([11,22,33,44,55,66,77,88,99])
print(arr_1d[-3:]) # [77,88,99]
print(arr_1d[-3::-1]) # [77,.....11]
print(arr_1d[-3:9:-1]) # []
print(arr_1d[-3:-6:-1]) # [77,66,55]
print(arr_1d[-3:0:-1]) # [77,66,55,44,33,22]
print(arr_1d[5:4:2]) # []
print(arr_1d[5:9:2]) # [66,88]
print(arr_1d[8:0:-2]) # [99,77,55,33]
print(arr_1d[-4::-2]) # [66,44,22]
print(arr_1d[3:8:-3]) # []
print(arr_1d[5:11:2]) # [66,88]

[77 88 99]
[77 66 55 44 33 22 11]
[]
[77 66 55]
[77 66 55 44 33 22]
[]
[66 88]
[99 77 55 33]
[66 44 22]
[]
[66 88]


In [21]:
# slicing[start,stop,step] -> arr_2d[rows_slicing , columns_slicing ]
arr_2d = np.array([
    [1,2,3,4,5],
    [1,3,5,7,9],
    [2,4,6,8,0],
    [5,4,3,2,1]
])

print(arr_2d[1:3 , 2:4]) # [[5,7][6,8]]

[[5 7]
 [6 8]]


In [22]:
print(arr_2d[-3::1 , 3::-1]) # [[7,5,3,1][8,6,4,2][2,3,4,5]]

[[7 5 3 1]
 [8 6 4 2]
 [2 3 4 5]]


In [23]:
arr_2d = np.array([
    [1,2,3,4,5],
    [1,3,5,7,9],
    [2,4,6,8,0],
    [5,4,3,2,1]
])

print(arr_2d[3::-2 , 1:4:3]) # [[4][3]]
# [5,4,3,2,1]
# [1,3,5,7,9]

[[4]
 [3]]


In [24]:
arr_2d = np.array([
    [1,2,3,4,5],
    [1,3,5,7,9],
    [2,4,6,8,0],
    [5,4,3,2,1]
])

print(arr_2d[2:5 , 2:5:-2]) # []
#  [2,4,6,8,0]
#  [5,4,3,2,1]

[]


In [25]:
arr_2d = np.array([
    [1,2,3,4,5],
    [1,3,5,7,9],
    [2,4,6,8,0],
    [5,4,3,2,1]
])

print(arr_2d[2:5 , 2:5:2]) # [[6,0][3,1]]
#  [2,4,6,8,0]
#  [5,4,3,2,1]

[[6 0]
 [3 1]]


In [26]:
arr_2d = np.array([
    [1,2,3,4,5],
    [1,3,5,7,9],
    [2,4,6,8,0],
    [5,4,3,2,1]
])

print(arr_2d[:, ::-2])

[[5 3 1]
 [9 5 1]
 [0 6 2]
 [1 3 5]]


In [27]:
arr_2d = np.array([
    [1,2,3,4,5],
    [1,3,5,7,9],
    [2,4,6,8,0],
    [5,4,3,2,1]
])

print(arr_2d[::-1, ::-1])
# First Row Reverse
# [5,4,3,2,1]
# [2,4,6,8,0]
# [1,3,5,7,9]
# [1,2,3,4,5]

# Then Column Reverse
# [1,2,3,4,5]
# [0,8,6,4,2]
# [9,7,5,3,1]
# [5,4,3,2,1]

[[1 2 3 4 5]
 [0 8 6 4 2]
 [9 7 5 3 1]
 [5 4 3 2 1]]


In [28]:
# Slicing in 3D Array [depth,row,col] -> [depth_slicing , row_slicing , col_slicing]
arr_3d = np.array([
    [[11,22,33,44],
     [22,44,66,88],
     [11,33,55,77],
    ],
    [[66,77,88,99],
     [11,55,77,99],
     [22,44,66,88],
    ]
])
arr_3d[:,:,::-1] # Complete 3D Array with reversed Columns

array([[[44, 33, 22, 11],
        [88, 66, 44, 22],
        [77, 55, 33, 11]],

       [[99, 88, 77, 66],
        [99, 77, 55, 11],
        [88, 66, 44, 22]]])

In [29]:
arr_3d = np.array([
    [[11,22,33,44],
     [22,44,66,88],
     [11,33,55,77],
    ],
    [[66,77,88,99],
     [11,55,77,99],
     [22,44,66,88],
    ]
])
arr_3d[1::2 , 0:3:2, ::-3] 
# Depth
#      [66,77,88,99],
#      [11,55,77,99],
#      [22,44,66,88]

# rows 
# [66,77,88,99]
# [22,44,66,88]

# Cols
# [99,66]
# [88,22]

array([[[99, 66],
        [88, 22]]])

In [31]:
arr_3d = np.array([
    [[11,22,33,44],
     [22,44,66,88],
     [11,33,55,77],
    ],
    [[66,77,88,99],
     [11,55,77,99],
     [22,44,66,88],
    ]
])
print(arr_3d[-2,2,0]) #  11
arr_3d[-2: , -1: , 0:3:2]

# [11,33,55,77] # [11,55]
# [22,44,66,88] # [22,66]

11


array([[[11, 55]],

       [[22, 66]]])

In [32]:
arr_3d = np.array([
    [[11,22,33,44],
     [22,44,66,88],
     [11,33,55,77],
    ],
    [[66,77,88,99],
     [11,55,77,99],
     [22,44,66,88],
    ]
])
arr_3d[0, -2::2, -3::-2] # 44

array([[44]])

In [33]:
arr_3d = np.array([
    [[11,22,33,44],
     [22,44,66,88],
     [11,33,55,77],
    ],
    [[66,77,88,99],
     [11,55,77,99],
     [22,44,66,88],
    ]
])
arr_3d[-2::2, ::-2 ,2:4:-1] # []

array([], shape=(1, 2, 0), dtype=int32)

In [34]:
arr_3d = np.array([
    [[11,22,33,44],
     [22,44,66,88],
     [11,33,55,77],
    ],
    [[66,77,88,99],
     [11,55,77,99],
     [22,44,66,88],
    ]
])
arr_3d[-2::2, ::-2 ,2:4:]

array([[[55, 77],
        [33, 44]]])

In [35]:
# Masking -> Uses a boolean array of the same shape to filter the values. 
arr_1d = np.array([11,22,33,44,55,66,77,88,99])
mask_arr = np.array([True,False,False,False,True,False,True,False,True])
print(arr_1d[mask_arr]) # [11,55,77,99]

[11 55 77 99]


In [36]:
# arr_2d [Masking]
arr_2d = np.array([
    [1,2,3,4,5],
    [1,3,5,7,9],
    [2,4,6,8,0],
    [5,4,3,2,1]
])

mask_2d = np.array([
    [True,False,True,True,True],
    [False,True,True,False,True],
    [True,False,True,True,False],
    [True,False,False,True,False]
])
print(arr_2d[mask_2d]) # Flatten up

[1 3 4 5 3 5 9 2 6 8 5 2]


In [37]:
arr_3d = np.array([
    [[11,22,33,44],
     [22,44,66,88],
     [11,33,55,77],
    ],
    [[66,77,88,99],
     [11,55,77,99],
     [22,44,66,88],
    ]
])

mask_3d = np.array([
    [[True,False,False,True],
     [False,True,True,False],
     [True,False,True,False],
    ],
    [[False,False,True,True],
     [True,True,False,False],
     [False,True,False,True],
    ]
])

print(arr_3d[mask_3d])

[11 44 44 66 11 55 88 99 11 55 44 88]
